apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: app
        image: nginx:1.25
        ports:
        - containerPort: 80
